services:
  https-portal:
    container_name: "https-portal"
    image: steveltn/https-portal:1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      STAGE: "production"
      DOMAINS: "merry-christmas-2024.kuama.net -> http://webapp:3000" #
  webapp:
    container_name: "webapp"
    image: kuamadev/merry-christmas-webapp:${APP_VERSION}
    restart: always
